# Generated by Django 4.2.23 on 2025-07-22 03:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=32, unique=True)),
                ('password', models.CharField(default='', max_length=64)),
                ('name', models.CharField(default='', max_length=32)),
                ('role', models.CharField(choices=[('student', '学生'), ('teacher', '老师')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='新会话', max_length=100)),
                ('coze_conversation_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='api.user')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
