# Generated by Django 4.1 on 2025-07-15 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_name_user_role_alter_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('title', models.CharField(max_length=100, verbose_name='会话标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='会话开始时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='会话更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('user_input', models.TextField(verbose_name='用户输入')),
                ('agent_output', models.TextField(verbose_name='智能体输出')),
                ('turn', models.IntegerField(verbose_name='对话轮次')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='对话时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='app.conversation', verbose_name='所属会话')),
            ],
        ),
    ]
