# Generated by Django 4.1 on 2025-07-15 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_conversation_dialogue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='user_id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='app.user', verbose_name='用户'),
            preserve_default=False,
        ),
    ]
