# Generated by Django 4.1 on 2025-07-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_conversation_user_id_remove_dialogue_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialogue',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Dialogue',
        ),
    ]
