# Generated by Django 4.2.23 on 2025-07-22 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_conversation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
