# Generated by Django 4.2.23 on 2025-07-27 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_conversation_group_dialogue_conversation_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='user',
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='app.user'),
        ),
    ]
